version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "8002:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mypass123!
      - MYSQL_DATABASE=EmployeeDB
      - MYSQL_USER=adwait
      - MYSQL_PASSWORD=Mypass123!
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["/var/lib/jenkins/workspace/mysql_dotnet_angular/ThirdRepo/wait-for-it.sh", "mysql:3306", "--", "docker-entrypoint.sh", "--default-authentication-plugin=mysql_native_password"]

  webapi:
    image: my-first-image
    ports:
      - "50306:80"
    networks:
      - mynetwork
    depends_on:
      - mysql
    command: ["/var/lib/jenkins/workspace/mysql_dotnet_angular/ThirdRepo/wait-for-it.sh", "mysql:3306", "--", "your-webapi-start-command"]

  angularapp:
    image: my-second-image
    ports:
      - "4201:4200"
    networks:
      - mynetwork
    depends_on:
      - webapi
    command: ["/var/lib/jenkins/workspace/mysql_dotnet_angular/ThirdRepo/wait-for-it.sh", "webapi:80", "--", "your-angularapp-start-command"]

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
